name: Update README

on:
  schedule:
    - cron: '0 0 */2 * *'  # Runs at 00:00 UTC on even days of the month (2, 4, 6,....30)
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update README
      run: |
        python .github/scripts/update_readme.py
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_REPO_TOKEN_FINE }}

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add README.md .last_images.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with random image" && git push)
